# Generated by Django 3.2.16 on 2023-09-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20230903_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={},
        ),
        migrations.AddConstraint(
            model_name='birthday',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'birthday'), name='Unique person constraint'),
        ),
    ]
